### ISSUE TITLE
Formatting in brackets can be confusing

### ISSUE THREAD

**Issue by danmarshall** [microsoft/ContributorLicenseAgreement#101]
Hello, I have a contributor who signed the CLA according to the bot's prompt:

```
@microsoft-github-policy-service agree [company="{your company}"]
```

[Their reply](https://github.com/microsoft/maker.js/pull/551#issuecomment-1404742036) included the brackets:

> @microsoft-github-policy-service agree [company="self"]

My initial impression of the prompt was also taken literally - it wasn't immediately clear to me that this was syntactic and the brackets were to indicate the optional clause. Perhaps the prompt might include the examples as [shown in the readme](https://github.com/microsoft/ContributorLicenseAgreement#accepting):

```
If you are contributing on behalf of yourself:
@microsoft-github-policy-service agree

If you are contributing on behalf of a company:
@microsoft-github-policy-service agree company="your company"
```

**Comment by DragosDanielBoia** [comment]
@danmarshall thx for the feedback/suggestions, a good one, we will address it.
