### ISSUE TITLE
Pull request to add policies/cla.yml is not commented by bot

### ISSUE THREAD

**Issue by lostmsu** [microsoft/ContributorLicenseAgreement#121]
See https://github.com/pythonnet/.github/pull/1

According to README in ContributorLicenseAgreement

> Create a seperate PR for this, **the policy service will create a comment** example bellow.

Policy service is not creating a comment under that PR.

**Comment by DragosDanielBoia** [comment]
@lostmsu will allow your org today and let you know, right now your org is not part if the external allowed org

**Comment by DragosDanielBoia** [comment]
@lostmsu is done, you will need to re-pushed the files and then should work

**Comment by lostmsu** [comment]
@DragosDanielBoia can you clarify what do you mean by "re-pushed the files"? I amended the commit in that pull request, and I still see no comment from a bot. Should I reopen the pull request?

**Comment by DragosDanielBoia** [comment]
> @DragosDanielBoia can you clarify what do you mean by "re-pushed the files"? I amended the commit in that pull request, and I still see no comment from the bot. Should I reopen the pull request?

Do a small edit and do a git push again.

**Comment by lostmsu** [comment]
You mean make a new commit?
Might make sense to handle amended commits too.

**Comment by lostmsu** [comment]
@DragosDanielBoia creating a new commit does not seem to work either.

Could that be because I previously signed the CLA with the old style bot?

**Comment by DragosDanielBoia** [comment]
@lostmsu can you add me admin on the org to see what's going on. You can remove me after.

**Comment by Luckymhe** [comment]
List of Approved Users
If your company has an agreement with Microsoft where only certain users are allowed to make contributions on behalf of your company, then you can specify the users via a CSV file titled approvedUsers.csv which should be located inside the company's repo. The list is global per CLA content link and has to be specified only once, [example here](https://github.com/microsoft/.github/blob/main/policies/cla.yml).

**Comment by jeffwilcox** [comment]
Closing - but if this is still an issue, let us know.
