### ISSUE TITLE
Support a GitHub comment trigger for re-running the CLA process

### ISSUE THREAD

**Issue by jeffhandley** [microsoft/ContributorLicenseAgreement#123]
Any time the CLA bot fails to run on a PR (for various reasons), contributors and maintainers have to remember the best way to force the bot to rerun itself. A `@microsoft-github-policy-service rerun` command or something similar would be very useful. Simply tagging `@microsoft-github-policy-service` or issuing `@microsoft-github-policy-service help` could even yield a comment that talks about when `rerun` is needed and how to use it.

Closing and reopening the PR is our go-to stop-gap, but that is an annoying step to have to take, especially when there are PR checks that take hours to run and we want to avoid stopping or rerunning them.

**Comment by DragosDanielBoia** [comment]
thanks for the feedback @jeffhandley , today github had a lot of issue, yes is going to be useful to implement this command "@microsoft-github-policy-service rerun" and we are going to do it.

**Comment by dougbu** [comment]
We in .NET Core-Eng field frequent requests about failed CLA checks and don't have good recommendations other than to close and reopen the affected PRs. Doing this would make our lives easier❕

**Comment by jeffwilcox** [comment]
Any input from people on `rerun` vs `reprocess` on the command?

**Comment by DragosDanielBoia** [comment]
@jeffhandley the rerun command is now in prod, this is the command for dotnet org:
Will close the issue.

@dotnet-policy-service rerun
