### ISSUE TITLE
Include org request

### ISSUE THREAD

**Issue by kalin-todorov** [microsoft/ContributorLicenseAgreement#130]
Hi guys,

We are trying to enable the policy, so I added the files from the readme to the repo: https://github.com/telerik/UI-For-UWP/pull/522
Please add our org to the allowed external orgs list.

Thanks,
Kalin
Telerik

**Comment by DragosDanielBoia** [comment]
@kalin-todorov in order to work you have to set the CLA under .github repo under policies folder

**Comment by kalin-todorov** [comment]
Hi @DragosDanielBoia,

Yeah, we were not sure how this should be done, so we created .github repo as well: https://github.com/telerik/.github/pull/1

Thanks,
Kalin

**Comment by DragosDanielBoia** [comment]
This is resolved.
