### ISSUE TITLE
Add a response message upon CLA acceptance

### ISSUE THREAD

**Issue by denelon** [microsoft/ContributorLicenseAgreement#131]
We would like to automate adding and removing labels on PRs when the bot informs the author about signing requirements. We can do this on the initial report since a comment is posted by the bot, but once the user "signs" the CLA there is no confirmation that the CLA was signed. If we had a message from the bot indicating the PR author has successfully signed the CLA then we could automate removing the label ourselves.

**Comment by DragosDanielBoia** [comment]
@denelon the confirmation that the CLA was signed is on the PR checks. See the image below:

![image](https://github.com/microsoft/ContributorLicenseAgreement/assets/19934057/96173cf1-7098-4393-94e5-4943b2acadb8)

**Comment by denelon** [comment]
@DragosDanielBoia is there a way to make a fabric bot rule trigger an action based on that?

**Comment by DragosDanielBoia** [comment]
> @DragosDanielBoia is there a way to make a fabric bot rule trigger an action based on that?

There is no way, today we don't look at the checks on the PR. We are going to open source the new FabricBot so people can start contributing.

**Comment by Luckymhe** [comment]
As per CLA policy 

Install [Microsoft GitHub Policy Service] (https://github.com/apps/microsoft-github-policy-service)
If you run on GH Enterprise Cloud, you have to give us (by creating an issue on this repo) the name of your enterprise.
Create a .github repo.
Add [platform context. yml](https://github.com/microsoft/.github/blob/main/policies/platformcontext.yml) under policies folder. You can push this directly.
Add [cla. yml](https://github.com/microsoft/.github/blob/main/policies/cla.yml) under policies folder. Create a separate PR for this, the policy service will create a comment example bellow. After you merge the PR, CLA policy will be activated across the entire org. image
