### ISSUE TITLE
CLA bot not responding on PRs

### ISSUE THREAD

**Issue by aramase** [microsoft/ContributorLicenseAgreement#140]
The bot is not running the CLA checks on the PR and is blocking PR merge.

ref: 
https://github.com/Azure/azure-workload-identity/pull/1008
https://github.com/Azure/azure-workload-identity/pull/999

**Comment by imatiach-msft** [comment]
+1 seeing this broken in our OSS microsoft repos as well, like this one:
https://github.com/microsoft/responsible-ai-toolbox/pull/2138

**Comment by DragosDanielBoia** [comment]
We had an issue, please @aramase/@imatiach-msft either close and reopen the PRs, CLA will green the check

**Comment by aramase** [comment]
> Azure/azure-workload-identity#999

I already tried that on https://github.com/Azure/azure-workload-identity/pull/999 but no dice!

**Comment by DragosDanielBoia** [comment]
> > We had an issue, please @aramase/@imatiach-msft either close and reopen the PRs, CLA will green the check
> 
> I already tried that on [Azure/azure-workload-identity#999](https://github.com/Azure/azure-workload-identity/pull/999) but no dice!

@aramase/@imatiach-msft  Done
