### ISSUE TITLE
No instruction to sign .NET Foundation CLA

### ISSUE THREAD

**Issue by AptiviCEO** [microsoft/ContributorLicenseAgreement#143]
I made my first contribution to a project which is supported by .NET Foundation: https://github.com/nunit/docfx-action. This is my first contribution: https://github.com/nunit/docfx-action/pull/32. However, when I checked the pull request status, I saw that it said:

Contributor License Agreement is not agreed yet.
This check verifies that the author has agreed to a CLA with Microsoft.

I searched Google on how to sign a CLA, but I found nothing, so it looks impossible to sign a CLA. Can anybody point me to how to sign a CLA?

**Comment by DragosDanielBoia** [comment]
@pkgw a comment on the PR should have been generated to explain what you need to do. Can you please try to push a small change to the PR and see if tje comment is showing up?

**Comment by AptiviCEO** [comment]
@DragosDanielBoia I pushed a commit to the fork in question, and even edited the PR title and description, but there is still no comment from the CLA bot.

The PR is not merged and is still waiting for the CLA comment.

Tried commenting "@microsoft-github-policy-service agree", but no change.

**Comment by jeffwilcox** [comment]
@ChrisSfanos anything you think we should change in the docs or point to on the .NET specific points before closing this?

**Comment by AptiviCEO** [comment]
@JohannesLampel @dotnet-policy-service agree worked! Thanks!

Proof: https://github.com/nunit/docfx-action/pull/32/checks?check_run_id=17148830822

**Comment by ChrisSfanos** [comment]
I don't know if we really have any content that is .NET foundation specific (I've had more than one comment where someone tried the microsoft CLA agree vs the dotnet agree.  I'm open to updating/adding content to the README that calls out the dotnet CLA if we think that's a good spot for it - thoughts?

**Comment by jeffwilcox** [comment]
Chris is this something you still want to do, or should we resolve at not planned?

**Comment by ChrisSfanos** [comment]
I think we are ok to close this for now - not a ton of new projects getting onboarded so ok to close
