### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by jsmanrique** [microsoft/ContributorLicenseAgreement#144]
I've seen that the repository is listed as MIT license, but checking files headers I've seen they mention "the Microsoft License".
<img width="757" alt="Captura de Pantalla 2023-08-29 a las 12 41 59" src="https://github.com/microsoft/ContributorLicenseAgreement/assets/1178305/68eae843-33ac-40cd-8a75-7aac0dc810c4">

Which one is the right one?

**Comment by JohannesLampel** [comment]
Thanks for reporting this. We have updated the project headers.
