### ISSUE TITLE
No longer working in my repo

### ISSUE THREAD

**Issue by makubacki** [microsoft/ContributorLicenseAgreement#149]
Could not get back a status from a PR even after several pushes.

https://github.com/microsoft/mu_rust_hid/pull/3

Appears similar to issues our team has filed in the past like this one https://github.com/microsoft/ContributorLicenseAgreement/issues/72.

**Comment by JohannesLampel** [comment]
We had an incident yesterday causing the CLA service to be temporarily unavailable. This is resolved now.
