### ISSUE TITLE
How to contributions by bots?

### ISSUE THREAD

**Issue by Piedone** [microsoft/ContributorLicenseAgreement#161]
Like this one: https://github.com/OrchardCMS/OrchardCore/pull/15036. The bot won't be able to accept the CLA. I'd argue, but IANAL, that it needn't either, and we can just merge the PR. Can you help, please?

**Comment by Piedone** [comment]
Any news here? @DragosDanielBoia can you help, perhaps?

**Comment by DragosDanielBoia** [comment]
@Piedone [allcontributors](https://github.com/apps/allcontributors) is an app, for bots to be allowed to merge you have to add them into the CLA config list as a bypass user, https://github.com/OrchardCMS/.github/blob/main/policies/cla.yml

**Comment by Piedone** [comment]
Ah, thanks, changed our config.
