### ISSUE TITLE
Auto-hide comments after CLA is agreed

### ISSUE THREAD

**Issue by adamjstewart** [microsoft/ContributorLicenseAgreement#166]
The comments that the bot posts on PRs are very long and detailed. This is helpful before it's signed, but verbose afterwards. I wonder if it's possible to automatically hide the comments being made on a PR after the CLA is signed.

**Comment by Piedone** [comment]
For us in https://github.com/OrchardCMS/OrchardCore it seems that the bot comments actually vanish after a CLA accept, which perhaps solve your request, but seems very confusing to me.

**Comment by adamjstewart** [comment]
Huh, it also seems to vanish now for me. It could have been a temporary issues, not sure. Let's close for now unless someone reports a similar issue.
