### ISSUE TITLE
Bot posting multiple times

### ISSUE THREAD

**Issue by adamjstewart** [microsoft/ContributorLicenseAgreement#167]
In https://github.com/microsoft/torchgeo/pull/1908, the bot posted the same comment 3 times (I hid them because they were too long). Seems like a bug to me.

**Comment by Saschaym** [comment]
version.json

**Comment by Saschaym** [comment]
b210abbebdd01f144889be8307ae22f6d31d2dd3

**Comment by Saschaym** [comment]
.gitignore
