### ISSUE TITLE
Not able to agree to CLA

### ISSUE THREAD

**Issue by vgamayunov** [microsoft/ContributorLicenseAgreement#57]
I am not able to agree to CLA. All attempts to write a comment to "@microsoft-github-policy-service" are not successful. For example:
![image](https://user-images.githubusercontent.com/74012931/196163461-27ab9dd3-588b-4e58-8d10-7e9a2cdd6537.png)

This is the PR which is blocked: https://github.com/Azure/az-hop/pull/1140

I get no reply from the bot to this command: @microsoft-github-policy-service agree company="Microsoft"

**Comment by benbp** [comment]
@vgamayunov I am still seeing issues with someone trying to agree on https://github.com/Azure/azure-sdk-for-go/pull/18923. Is there something we should be doing differently here? Thanks!
