### ISSUE TITLE
microsoft-github-policy-service agreement not working

### ISSUE THREAD

**Issue by lisamurphy-msft** [microsoft/ContributorLicenseAgreement#63]
Greetings,

We are trying to get this PR approved: https://github.com/Azure/missionlz/pull/761
It keeps getting stuck on the Licensing/CLA requirements and even though the author has input the correct information to sign the CLA it is not being approved. Please advise.

Thanks!

**Comment by DragosDanielBoia** [comment]
thanks for letting us know, @JohannesLampel is going to check this and let you know

**Comment by DragosDanielBoia** [comment]
this has been resolved
