### ISSUE TITLE
Issue with CLA signing, not able to sign CLA

### ISSUE THREAD

**Issue by sushil490023** [microsoft/ContributorLicenseAgreement#77]
I am not able to agree to CLA. I did write a comment to @microsoft-github-policy-service agree company="microsoft" which is not  successful. 

<img width="702" alt="image" src="https://user-images.githubusercontent.com/25101734/199414813-845eb19d-495f-4054-9cb3-874e5e87f64b.png">

PR link : https://github.com/Azure/azure-rest-api-specs/pull/21128
Can someone help in unblocking this ??

**Comment by JohannesLampel** [comment]
@sushil490023 the problem should be resolved now.
