### ISSUE TITLE
Bot not responding to CLA comment

### ISSUE THREAD

**Issue by jnilau** [microsoft/ContributorLicenseAgreement#80]
Our intern followed the CLA bot's instructions for his PR (https://github.com/microsoft/azure-pipelines-agent/pull/3944) but the license requirement is still blocking the PR. Please let me know if I missed something.

**Comment by JohannesLampel** [comment]
@jnilau the issue should be resolved now.

**Comment by jnilau** [comment]
@JohannesLampel Thank you for the quick turnaround!
