### ISSUE TITLE
CLA bot seems stuck

### ISSUE THREAD

**Issue by achamayou** [microsoft/ContributorLicenseAgreement#85]
Good morning,

Two PRs on our repo are blocked on the CLA bot, even though the contributor has followed instructions:

https://github.com/microsoft/CCF/pull/4563
https://github.com/microsoft/CCF/pull/4563#issuecomment-1328079198

https://github.com/microsoft/CCF/pull/4641
https://github.com/microsoft/CCF/pull/4641#issuecomment-1328079376

The bot seems to be stuck:

![image](https://user-images.githubusercontent.com/4016369/204508857-32f503dc-c3b5-4ba1-90d2-283678e36569.png)

I am not sure this is the right place to report this issue, but I found nowhere else, and I was encouraged by the existence of past issues, such as #80 and #77. Any help would be much appreciated!

**Comment by gabrielsiewe-ms** [comment]
Hello @JohannesLampel we are facing a similar issue with:
https://github.com/microsoft/hackthehire/pull/1/checks?check_run_id=9813159154

Is there anything we can do to get pass this issue?

**Comment by achamayou** [comment]
@JohannesLampel they have indeed, thank you!

@gabrielsiewe-ms I see your PR is now merged, so closing this issue as resolved.

**Comment by gabrielsiewe-ms** [comment]
@achamayou the PR is merged but the process is still running. Is that normal? Will it ever stop?

**Comment by JohannesLampel** [comment]
This is just a GitHub thing.
There is no actual process running. It will say running until we report that it has completed. Since the pr is closed we will not report this as completed.

**Comment by gabrielsiewe-ms** [comment]
@JohannesLampel thanks for the explanation. Just to make sure I understand, it will say "Running" forever since the PR is closed and you won't report it as completed? Would reopening the PR stop it from saying "Running" forever? Or will it just stop saying "Running" at some point in the future, even if you won't report it as completed?

**Comment by JohannesLampel** [comment]
It will only mark the check as completed if the pr was open at the point in time where the cla was successfully signed.
Otherwise it will stay in the running state indefinitely.
