### ISSUE TITLE
PR is Stuck by License Check

### ISSUE THREAD

**Issue by msJinLei** [microsoft/ContributorLicenseAgreement#90]
Hi team,

My PR is stuck by license check https://github.com/Azure/azure-powershell/pull/20341
Anyway to run the recheck?
Thanks

**Comment by DragosDanielBoia** [comment]
the issue has been resolved will close this one

**Comment by msJinLei** [comment]
> the issue has been resolved will close this one

@DragosDanielBoia
I recheck the PR by close and re-open the PR. Is there any other way to do it?
