### ISSUE TITLE
CLA bot not responding on PRs

### ISSUE THREAD

**Issue by aramase** [microsoft/ContributorLicenseAgreement#95]
The bot is not running the CLA checks on the PR and is blocking PR merge.

ref: 
https://github.com/Azure/azure-workload-identity/pull/712

**Comment by JohannesLampel** [comment]
Hi @aramase 
We had an incident earlier today. I've updated the cla check on your pr, you should be good.
In case this happens again, and you don't want to wait for me, just close and reopen the pr.
Sorry for the inconvenience.
